{% set name = "benchscofi" %}
{% set version = "9999" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ name }}-{{ version }}.tar.gz"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - pip
    - python

  run:
    - stanscofi >=2.0.0
    - numpy ==1.19.4
    - tensorflow ==2.4.3
    - pulearn >=0.0.7
    - torch >=2.0.1
    - fastai >=2.7.12
    - torch_geometric >=2.3.1
    - pyFFM >=0.0.7
    - protobuf ==3.9.*
    - pydantic ==1.9.*
    - pytorch-lightning >=2.0.5
    - torchmetrics >=1.0.1

test:
  imports:
    - benchscofi
    - benchscofi.utils

about:
  home: https://github.com/RECeSS-EU-Project/benchscofi
  license: MIT
  license-file: LICENSE
  summary: "Package which contains collaborative filtering-based algorithms for drug repurposing."

extra:
  recipe-maintainers:
    - RECeSS-EU-Project
